# Add homebrew binaries
export PATH="/usr/local/sbin:$PATH"

export PATH="$HOME/bin:$PATH:$MYSQL"

# Change XDG config directory
export XDG_CONFIG_HOME="$HOME/.config"

# Go
export GOPATH=$HOME/go

# Go packages
export PATH="$PATH:/Users/aclapinpepin/go/bin"

# Java
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home"
export PATH="$ES_HOME/bin:$JAVA_HOME/bin:$PATH"

# Rust && Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Python3
# NOTE: Mamba is overriding the default Python3
# export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$PATH:/Users/aclapinpepin/Library/Python/3.11/bin"
export PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:$PATH"

# LLVM
export PATH="/usr/local/opt/llvm/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/aclapinpepin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/aclapinpepin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/aclapinpepin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/aclapinpepin/google-cloud-sdk/completion.zsh.inc'; fi

# foundry https://github.com/foundry-rs/foundry
export PATH="$PATH:/Users/aclapinpepin/.foundry/bin"

# Solana
export PATH="/Users/aclapinpepin/.local/share/solana/install/active_release/bin:$PATH"

# gpg
export GPG_TTY=$(tty)
