# Add homebrew binaries
export PATH="/usr/local/sbin:$PATH"

export PATH="$HOME/bin:$PATH:$MYSQL"

# Go
export GOPATH=$HOME/go

# Elasticsearch
export ES_HOME="/Applications/elasticsearch-6.5.4"

# Java
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home"
export PATH="$ES_HOME/bin:$JAVA_HOME/bin:$PATH"

# Rust && Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Python3
export PATH="$HOME/Library/Python/3.7/bin:$PATH"

# LLVM
export PATH="/usr/local/opt/llvm/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/aclapinpepin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/aclapinpepin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/aclapinpepin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/aclapinpepin/google-cloud-sdk/completion.zsh.inc'; fi

# gpg
export GPG_TTY=$(tty)
