# Load and initialize the completion system; Must be loaded first!
autoload -Uz compinit
compinit -C

for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

alias vim="nvim"
alias vi="nvim"

# Fish-like autosuggestions for zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Fish shell like syntax highlighting for zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Specify a dump file location for compdump
COMPDUMP="${ZDOTDIR:-$HOME}/.zsh/.zcompdump"

# Add the completion directory to the fpath
fpath=($HOME/.zsh/completions ${fpath[@]})

# Evoke starship prompt (must be at the end of .zshrc)
eval "$(starship init zsh)"
