source ~/.zplug/init.zsh

zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure"
zplug "zsh-users/zsh-syntax-highlighting", defer:0
zplug 'zsh-users/zsh-completions', defer:0

zplug load

for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

ensure_tmux_is_running

alias vim="nvim"
alias vi="nvim"
